name: donation_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  connectivity: ^3.0.6
  intl: ^0.17.0
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  flutter_screenutil: ^5.0.0+2
  shared_preferences: ^2.0.15
  cloud_firestore: ^3.1.17
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.2.3
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  color: "#accceb"
  image: "assets/splash.png"
  android12: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/menu_icons/
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf